Deliver/Deliver/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls')),
    path('Users/', include('user.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Deliver/products/urls.py
from django.urls import path
from .views import *

app_name = 'products'


urlpatterns = [
    path('',items, name='home'),
    path('details/<pk>/', details, name='detail'),
]

Deliver/user/urls.py
from django.urls import path 
from .views import *


app_name = 'user'

urlpatterns = [
    path("signup/",CustomerSignUpView.as_view(), name="signup"),
    path("seller-signup/",SellerSignUpView.as_view(), name="reg"),
    path('login/',LoginView.as_view(), name='login'),
    path('logout/', Logout_view , name='logout'),
]

   

Deliver/products/models.py
from django.db import models
from user.models import User



class Categories(models.Model):        
    category_name = models.CharField(max_length=200)

    class Meta:
        ordering = ['category_name',]
        verbose_name_plural = 'Categories'
        
    def __str__(self):
        return self.category_name

class Product(models.Model):
    category = models.ForeignKey(Categories, related_name='type',on_delete=models.CASCADE, blank=True, null=True)
    name = models.CharField(max_length = 250)
    description = models.TextField(blank=True, null=True)
    price = models.DecimalField(max_digits = 30, decimal_places=2)
    image = models.ImageField(upload_to='uploads/', null=True)
    is_available = models.BooleanField(default=True)
    product_by = models.ForeignKey(User,on_delete=models.CASCADE, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name
    
   

Deliver/products/views.py
from django.shortcuts import render, get_object_or_404
from .models import Product

def items(request):
    product = Product.objects.all()
    return render(request, 'product/home.html', {'products': product,})


def details(request, pk):
    product = get_object_or_404(Product, id=pk)
    related_items = Product.objects.filter(category=product.category).exclude(pk=pk)
    return render(request, 'product/details.html', {'product':product,
                                                    'related':related_items} )

Deliver/products/templates/product/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% load static %}
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>{% block title%}{%endblock%} | Micheal & Yolanda </title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <!-- <link href="{%static 'property/assets/img/letter-v.png' %}" rel="icon" type="image/png"> -->

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{%static 'property/assets/vendor/animate.css/animate.min.css' %}" rel="stylesheet">
  <link href="{%static 'property/assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{%static 'property/assets/vendor/bootstrap-icons/bootstrap-icons.css '%}" rel="stylesheet">
  <link href="{%static 'property/assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{%static 'property/assets/css/style.css' %}" rel="stylesheet">
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/5.3.0/css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@splidejs/splide@3.6.12/dist/css/splide.min.css">

  <!-- =======================================================
  * Template Name: EstateAgency
  * Template URL: https://bootstrapmade.com/real-estate-agency-bootstrap-template/
  * Updated: Mar 17 2024 with Bootstrap v5.3.3
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
  <style>
    .property-container {
      display: flex;
      align-items: flex-start;
      gap: 2rem;
      /* Adjust the gap between the image and the description as needed */
    }

    .property-image {
      flex: 0 0 auto;
      /* The image will take up only as much space as it needs */
    }

    .property-details {
      flex: 1 1 auto;
      /* The details will take up the remaining space */
    }

    .property-description {
      margin-top: 0rem;
      /* Adjust the margin as needed */
    }
  </style>
</head>

<body>

  <!-- ======= Property Search Section ======= -->
  <div class="click-closed"></div>
  <!--/ Form Search Star /-->
  <div class="box-collapse">
    <div class="title-box-d">
      <h3 class="title-d">Search Products</h3>
    </div>
    <span class="close-box-collapse right-boxed bi bi-x"></span>
    <div class="box-collapse-wrap form">
      <form class="form-a">
        <div class="row">
          <div class="col-md-12 mb-2">
            <div class="form-group">
              <label class="pb-2" for="Type">Keyword</label>
              <input type="text" class="form-control form-control-lg form-control-a" placeholder="Keyword">
            </div>
          </div>
          <div class="col-md-6 mb-2">
            <div class="form-group mt-3">
              <label class="pb-2" for="Type">Type</label>
              <select class="form-control form-select form-control-a" id="Type">
                <option>All Type</option>
                <option>Fast Food</option>
                <option>Drinks</option>
                <option>Fashion</option>
              </select>
            </div>
          </div>
          <div class="col-md-6 mb-2">
            <div class="form-group mt-3">
              <label class="pb-2" for="city">City</label>
              <select class="form-control form-select form-control-a" id="city">
                <option>All City</option>
                <option>Kampala</option>
                <option>Mbale</option>
                <option>Jinja</option>
                <option>Nairobi</option>
              </select>
            </div>
          </div>
          <div class="col-md-6 mb-2">
            <div class="form-group mt-3">
              <label class="pb-2" for="price">Price Range</label>
              <select class="form-control form-select form-control-a" id="price">
                <option>Unlimite</option>
                <option>sh. 20,000</option>
                <option>sh. 50,000</option>
                <option>sh. 100,000</option>
                <option>sh. 150,000</option>
              </select>
            </div>
          </div>
          <div class="col-md-12">
            <button type="submit" class="btn btn-b">Search Producct</button>
          </div>
        </div>
      </form>
    </div>
  </div><!-- End Property Search Section -->>

  <!-- ======= Header/Navbar ======= -->
  <nav class="navbar navbar-default navbar-trans navbar-expand-lg fixed-top">
    <div class="container">
      <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#navbarDefault"
        aria-controls="navbarDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span></span>
        <span></span>
        <span></span>
      </button>
      <a class="navbar-brand text-brand" href="{% url 'products:home' %}">Micheal & <span
          class="color-b">Yolanda</span><br>
        <span>
          <h6>Fast Delivery Services</h6>
        </span></a>


      <div class="navbar-collapse collapse justify-content-end" id="navbarDefault">
        <ul class="navbar-nav ml-5">

          <li class="nav-item">
            <a class="nav-link active" href="{% url 'products:home' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link " href=" ">Products</a>
          </li>
          <li class="nav-item">
            <a class="nav-link mr-4" href=" ">Cart</a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
              aria-haspopup="true" aria-expanded="false">Hi,{{user.username}}</a>
            <div class="dropdown-menu">
              <a class="dropdown-item " href=" ">Orders</a>
              <a class="dropdown-item " href=" ">Checkout</a>
              <a class="dropdown-item " href=" ">Cart</a>
              <a class="dropdown-item " href=" ">Account Settings</a>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{%url 'user:logout' %}">Logout</a>
          </li>
          {% else %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
              aria-haspopup="true" aria-expanded="false">Account</a>
            <div class="dropdown-menu">
              <a class="dropdown-item " href="{% url 'user:login' %}">Login</a>
              <a class="dropdown-item " href="{% url 'user:signup' %}">SignUp</a>
            </div>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav><!-- End Header/Navbar -->

  {% block content %}
  {% endblock %}

  <!-- ======= Footer ======= -->
  <section class="section-footer">
    <div class="container">
      <div class="row">
        <div class="col-sm-12 col-md-4">
          <div class="widget-a">
            <div class="w-header-a">
              <h3 class="w-title-a text-brand">Micheal & Yolanda <br><span>
                  <h6>Fast Delivery Services</h6>
                </span></h3>
            </div>
            <div class="w-body-a">
              <p class="w-text-a color-text-a">
                Enim minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip exea commodo consequat duis
                sed aute irure.
              </p>
            </div>
            <div class="w-footer-a">
              <ul class="list-unstyled">
                <li class="color-a">
                  <span class="color-text-a">Phone .</span> +256-726615907
                </li>
                <li class="color-a">
                  <span class="color-text-a">Email .</span> ssenkungudenis76@gmail.com
                </li>
              </ul>
            </div>
          </div>
        </div>
        <div class="col-sm-12 col-md-4 section-md-t3">
          <div class="widget-a">
            <div class="w-header-a">
              <h3 class="w-title-a text-brand">The Company</h3>
            </div>
            <div class="w-body-a">
              <div class="w-body-a">
                <ul class="list-unstyled">
                  <li class="item-list-a">
                    <i class="bi bi-chevron-right"></i> <a href="#">Site Map</a>
                  </li>
                  <li class="item-list-a">
                    <i class="bi bi-chevron-right"></i> <a href="#">Legal</a>
                  </li>
                  <li class="item-list-a">
                    <i class="bi bi-chevron-right"></i> <a href="#">Agent Admin</a>
                  </li>
                  <li class="item-list-a">
                    <i class="bi bi-chevron-right"></i> <a href="#">Careers</a>
                  </li>
                  <li class="item-list-a">
                    <i class="bi bi-chevron-right"></i> <a href="#">Affiliate</a>
                  </li>
                  <li class="item-list-a">
                    <i class="bi bi-chevron-right"></i> <a href="#">Privacy Policy</a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
        <div class="col-sm-12 col-md-4 section-md-t3">
          <div class="widget-a">
            <div class="w-header-a">
              <h3 class="w-title-a text-brand">International sites</h3>
            </div>
            <div class="w-body-a">
              <ul class="list-unstyled">
                <li class="item-list-a">
                  <i class="bi bi-chevron-right"></i> <a href="#">Kenya</a>
                </li>
                <li class="item-list-a">
                  <i class="bi bi-chevron-right"></i> <a href="#">SouthSudan</a>
                </li>
                <li class="item-list-a">
                  <i class="bi bi-chevron-right"></i> <a href="#">DR Congo</a>
                </li>
                <li class="item-list-a">
                  <i class="bi bi-chevron-right"></i> <a href="#">Uganda</a>
                </li>
                <li class="item-list-a">
                  <i class="bi bi-chevron-right"></i> <a href="#">Singapore</a>
                </li>
                <li class="item-list-a">
                  <i class="bi bi-chevron-right"></i> <a href="#">Egypt</a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <nav class="nav-footer">
            <ul class="list-inline">
              <li class="list-inline-item">
                <a href="{%url 'products:home' %}">Home</a>
              </li>
              <li class="list-inline-item">
                <a href=" ">About</a>
              </li>
              <li class="list-inline-item">
                <a href="{%url 'products:home' %}">Products</a>
              </li>
              <li class="list-inline-item">
                <a href=" ">Blog</a>
              </li>
              <li class="list-inline-item">
                <a href=" ">Contact</a>
              </li>
            </ul>
          </nav>
          <div class="socials-a">
            <ul class="list-inline">
              <li class="list-inline-item">
                <a href="#">
                  <i class="bi bi-facebook" aria-hidden="true"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <i class="bi bi-twitter" aria-hidden="true"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <i class="bi bi-instagram" aria-hidden="true"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <i class="bi bi-linkedin" aria-hidden="true"></i>
                </a>
              </li>
            </ul>
          </div>
          <div class="copyright-footer">
            <p class="copyright color-text-a">
              &copy; Copyright
              <span class="color-a">Micheal&Yolanda</span> All Rights Reserved. <br>
            </p>
          </div>
          <div class="credits">
          </div>
        </div>
      </div>
    </div>
  </footer><!-- End  Footer -->

  <div id="preloader"></div>
  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i
      class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.3.0/js/bootstrap.bundle.min.js"></script>
  <script src="{%static 'property/assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{%static 'property/assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{%static 'property/assets/vendor/php-email-form/validate.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{%static 'property/assets/js/main.js' %}"></script>
  <script src="https://cdn.jsdelivr.net/npm/@splidejs/splide@3.6.12/dist/js/splide.min.js"></script>

</body>

</html> edit the icon to fit

Deliver/products/templates/product/details.html
{% extends 'product/base.html' %}
{% block title %} {{product.name}} {% endblock %}

{% load static %}
{% load humanize %}

{% block content %}
<section class="intro-single">
  <div class="container">
      <div class="row">
          <div class="col-md-12 col-lg-8">
              <div class="title-single-box">
                  <h1 class="title-single">{{product.name}}</h1>
                  <span class="color-text-a">{{product.category}}</span><br>
                  <span class="color-text-a">shs. {{product.price | intcomma}}</span>
              </div>
          </div>
      </div>
  </div>
</section>

<section>
  <div class="container">
    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-6 mb-4">
          <div class="property-image">
            <img class="w-full img-fluid" src="{{product.image.url}}" alt="Image">
          </div>
        </div>
        <div class="col-lg-6">
          <div class="property-details">
            <div class="title-box-d mb-4">
              <h3 class="title-d">Property Description</h3>
            </div>
            <div class="property-description">
              <p class="description color-text-a">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore veniam unde impedit quaerat harum,
                voluptatibus reprehenderit dignissimos modi consectetur expedita! Optio ad pariatur possimus rem
                obcaecati saepe. Ea, iure nihil!
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Enim distinctio alias animi quibusdam,
                voluptatum error quo! Omnis culpa est exercitationem et ex nihil, ipsa temporibus ipsam amet iure nam
                distinctio?
              </p>
              <ul class="nav nav-pills nav-pills-a nav-pills mb-4" id="pills-tab" role="tablist">
                <li class="nav-item">
                  <a class="nav-link active" id="pills-video-tab" data-bs-toggle="pill" href="#pills-video" role="tab"
                    aria-controls="pills-video" aria-selected="true">Cart Options</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" id="pills-map-tab" data-bs-toggle="pill" href="#pills-map" role="tab"
                    aria-controls="pills-map" aria-selected="false">Inquiries</a>
                </li>
              </ul>
              <div class="tab-content" id="pills-tabContent">
                <div class="tab-pane fade show active" id="pills-video" role="tabpanel"
                  aria-labelledby="pills-video-tab">
                  <div class="card border-secondary">
                    <div class="card-header bg-blue-200 border-0">
                      <h4 class="font-weight-semi-bold m-0 text-center">Add {{product.name}} to your Cart</h4>
                    </div>
                    <div class="card-body">
                      <div class="d-flex flex-column">
                        <div class="d-flex align-items-center">
                          <div class="quantity-controls d-flex align-items-center">
                            <h6 class="mr-2">Quantity:</h6> <!-- Added text 'Quantity' -->
                            <button type="button" class="btn btn-success ml-3 btn-sm px-3" onclick="decreaseQuantity()">-</button>
                            <span id="quantityDisplay" class="mx-2">1</span>
                            <button type="button" class="btn btn-success btn-sm px-3" onclick="increaseQuantity()">+</button>
                          </div>
                        </div>   
                        </div>
                        <form class="mt-3">
                          {% csrf_token %}
                          <input type="hidden" name="quantity" id="quantity" value="1">
                          <input type="hidden" name="override" value="False">
                          <button type="submit" class="btn btn-danger px-3 mb-2">
                            <i class="fa fa-shopping-cart mr-2"></i> Add To Cart
                          </button>
                          <a href="{% url 'products:home' %}" class="btn btn-primary px-3 mb-2">
                            <i class="fa fa-shopping-cart mr-2"></i> Continue Shopping
                          </a>
                          <a href="{% url 'products:home' %}" class="btn btn-primary px-3 mb-2">
                            <i class="fa fa-shopping-cart mr-2"></i> Request Delivery
                          </a>
                        </form>
                      </div>
                    </div>
                    
                  </div>
                </div>
                <div class="tab-pane fade" id="pills-map" role="tabpanel" aria-labelledby="pills-map-tab">
                  <div class="card border-secondary">
                    <div class="card-header bg-blue-200 border-0">
                      <h4 class="font-weight-semi-bold m-0 text-center">Send a Message</h4>
                    </div>
                    <div class="card-body">
                      <form>
                        <div class="form-group mt-2">
                          <label for="exampleInputPassword1">Content</label>
                          <textarea class="form-control"
                            placeholder="eg. how does the delivery work etc...."></textarea>
                        </div>
                        <button type="submit" class="btn btn-success btn-lg btn-block mt-3">Send</button>
                      </form>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <section class="section-property section-t8 bg-light py-5">
    <div class="container">
      <div class="row mb-4">
        <div class="col-md-12">
          <div class="title-wrap d-flex justify-content-between">
            <div class="title-box">
              <h2 class="title-a">Related Products</h2>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        {% for item in related %}
        <div class="col-md-6 col-lg-3 mb-4">
          <div class="card shadow-sm">
            <img src="{{ item.image.url }}" class="card-img-top" alt="{{ item.name }}">
            <div class="card-body">
              <h5 class="card-title">{{ item.name }}</h5>
              <p class="card-text">Price: shs. {{ item.price | intcomma }}</p>
              <a href="{% url 'products:detail' item.pk %}" class="btn btn-success">View Details</a>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </section>
</section>

<script>
  function decreaseQuantity() {
      var quantityDisplay = document.getElementById('quantityDisplay');
      var quantityInput = document.getElementById('quantity');
      var currentValue = parseInt(quantityDisplay.innerText);
      if (currentValue > 1) {
          quantityDisplay.innerText = currentValue - 1;
          quantityInput.value = currentValue - 1;  // Update the hidden input field
      }
  }

  function increaseQuantity() {
      var quantityDisplay = document.getElementById('quantityDisplay');
      var quantityInput = document.getElementById('quantity');
      var currentValue = parseInt(quantityDisplay.innerText);
      quantityDisplay.innerText = currentValue + 1;
      quantityInput.value = currentValue + 1;  // Update the hidden input field
  }
</script>
{% endblock %}

Deliver/products/templates/product/home.html
{% extends 'product/base.html' %}
{% block title %}HomePage{% endblock %}

{% load static %}
{% load humanize %}

{% block content %}
<section class="section-services section-t8 py-5">
  <div class="container">
    <div class="row mb-4">
      <div class="col-md-12">
        <div class="title-wrap d-flex justify-content-between">
          <div class="title-box">
            <h2 class="title-a">Our Services</h2>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-4">
        <div class="card-box-c foo shadow-sm">
          <div class="card-header-c d-flex align-items-center">
            <div class="card-box-ico">
              <span class="bi bi-cart"></span>
            </div>
            <div class="card-title-c">
              <h2 class="title-c">Delivery</h2>
            </div>
          </div>
          <div class="card-body-c">
            <p class="content-c">
              Sed porttitor lectus nibh. Cras ultricies ligula sed magna dictum porta. Praesent sapien massa,
              convallis a pellentesque nec, egestas non nisi.
            </p>
          </div>
          <div class="card-footer-c">
            <a href="#" class="link-c link-icon">Read more
              <span class="bi bi-chevron-right"></span>
            </a>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="card-box-c foo shadow-sm">
          <div class="card-header-c d-flex align-items-center">
            <div class="card-box-ico">
              <span class="bi bi-calendar4-week"></span>
            </div>
            <div class="card-title-c">
              <h2 class="title-c">Marketing</h2>
            </div>
          </div>
          <div class="card-body-c">
            <p class="content-c">
              Nulla porttitor accumsan tincidunt. Curabitur aliquet quam id dui posuere blandit. Mauris blandit
              aliquet elit, eget tincidunt nibh pulvinar a.
            </p>
          </div>
          <div class="card-footer-c">
            <a href="#" class="link-c link-icon">Read more
              <span class="bi bi-chevron-right"></span>
            </a>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="card-box-c foo shadow-sm">
          <div class="card-header-c d-flex align-items-center">
            <div class="card-box-ico">
              <span class="bi bi-card-checklist"></span>
            </div>
            <div class="card-title-c">
              <h2 class="title-c">Sell</h2>
            </div>
          </div>
          <div class="card-body-c">
            <p class="content-c">
              Sed porttitor lectus nibh. Cras ultricies ligula sed magna dictum porta. Praesent sapien massa,
              convallis a pellentesque nec, egestas non nisi.
            </p>
          </div>
          <div class="card-footer-c">
            <a href="#" class="link-c link-icon">Read more
              <span class="bi bi-chevron-right"></span>
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</section><!-- End Services Section -->

<section class="section-property section-t8 py-5 bg-light">
  <div class="container">
    <div class="row mb-4">
      <div class="col-md-12">
        <div class="title-wrap d-flex justify-content-between">
          <div class="title-box">
            <h2 class="title-a">Products</h2>
          </div>
          <div class="title-link">
            <h5>Search <span><button type="button" class="btn btn-b-n navbar-toggle-box navbar-toggle-box-collapse"
                  data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01">
                  <i class="bi bi-search"></i>
                </button></span></h5>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      {% for item in products %}
      <div class="col-sm-6 col-md-3 mb-4">
        <div class="card shadow-sm">
          <img src="{{ item.image.url }}" class="card-img-top" alt="{{ item.name }}">
          <div class="card-body">
            <h5 class="card-title">{{ item.name }}</h5>
            <p class="card-text">Price: shs. {{ item.price | intcomma }}</p>
            <a href="{% url 'products:detail' item.pk %}" class="btn btn-success">View Details</a>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</section><!-- End Latest Properties Section -->

{% endblock %}